services:
  - type: web
    name: el-concursillo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_new.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: el-concursillo-db
          property: connectionString
  - type: pserv
    name: el-concursillo-db
    env: postgresql
    plan: free
